name: news_application
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.0
  http: ^1.0.0
  hive: ^2.0.0
  hive_flutter: ^1.1.0
  cached_network_image: ^3.0.0
  intl: ^0.17.0
  get_it: ^7.6.8
  dartz: ^0.10.1
  url_launcher: ^6.3.0
  equatable: ^2.0.3
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.0.0
  hive_generator: ^2.0.1
  mockito: ^5.0.17
  bloc_test: ^9.1.7

flutter:
  uses-material-design: true
